FIX: Adding github_instance_url to checkpoint table (#427)
This field is used by the retry service and currently exist in the prod
table but not in the integration and autopush checkpoint tables.

This is causing this error in the cloud run retry job:

jsonPayload: {
error: "failed to retrieve checkpoint: failed to make read request to
BigQuery: googleapi: Error 400: Name github_instance_url not found
inside t at [1:99], invalidQuery"