Table function requires project qualification (#158)
Though the error message suggests this should be fine since its in the
same project.

```
  Error: Error creating Routine: googleapi: Error 400: Within a standard SQL table function, references to tables/views require explicit project IDs unless the entity is created in the same project that is issuing the query, but these references are not project-qualified: "github_metrics.raw_events", invalidQuery
  
    with module.github_metrics_aggregator.google_bigquery_routine.unique_events_by_date_type,
    on .terraform/modules/github_metrics_aggregator/terraform/bigquery.tf line 453, in resource "google_bigquery_routine" "unique_events_by_date_type":
   453: resource "google_bigquery_routine" "unique_events_by_date_type" {
```

Went ahead and fully qualified everything just to be safe.

Signed-off-by: Parker DeWilde <pdewilde@google.com>