chore: update Cloud Run module and Google provider version (#202)
This change fixes the error thrown when using legacy `automatic = true`
instead of new `auto {}` block inside of `google_secret_manager_secret`
`replication` block, introduced since Google Provider `>= 4.83.0`.

```
Error: Unsupported argument
248:     automatic = true

An argument named "automatic" is not expected here.
```